---
{{- if .Values.keda.enabled }}
{{- $svc := .Chart.Name }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $svc }}
  labels:
    app: {{ $svc }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ $svc }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  {{- with .Values.keda.fallback }}
  fallback:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.keda.advanced }}
  advanced:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  triggers:
    {{- toYaml .Values.keda.triggers | nindent 4 }}
{{- end }}
